import StyledComponentsRegistry from '@/lib/registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalStyles } from '@/styles/global'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Upwork clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/assets/images/global/favicon.png" type="image/x-icon" />
      </Head>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <GlobalStyles/>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
